### ISSUE TITLE
Can't sign in via GitHub when installed on Homescreen on iOS

### ISSUE THREAD

**Issue by SimonS** [successible/cleanslate#142]
I can sign in to the main `app.` instance on the web, both on my phone and on desktop. However, when I sign in (using the GH provider) after installing to home screen, it just returns me back to a sign in screen.

**Comment by paulzakin** [comment]
Unfortunately, I can’t replicate this behavior. I just tried and I was able to login on iOS to GitHub with it added to Home Screen. 

Can you try removing the app from your phone, adding it again, and trying again? Or maybe update your operating system if you haven’t already? Or maybe clear your cache?

Also, no one else has ever reported this particular behavior, which is often assigned that it has to do with the device rather than the app :(

**Comment by SimonS** [comment]
ha - removing and re adding seems to have fixed it. Apologies for the time waste :D

**Comment by paulzakin** [comment]
Not a problem!
