### ISSUE TITLE
Bug when editing ingredients in custom recipe

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#92]
I recorded a GIF which shows the bug better than any description I could make 😄

![bug](https://user-images.githubusercontent.com/131557313/233890475-14f6f441-d1a7-4f31-a84d-c621d692dd9b.gif)

I'm pretty sure this behavior isn't intended as I didn't find it in any other similar windows like custom foods or when picking foods from the known database.

**Comment by paulzakin** [comment]
So this actually is intended! Basically if you switch from unit X to unit Y, like count to gram, and it cannot be converted to a nice whole number it will be decimal. And since we probably cannot show the whole decimal (too long) we round it. Hence, we cannot convert it back perfectly. Alternatively, we could not do the conversion and simply keep the amount the same when toggling around. What do you think makes the most sense?

**Comment by sgomez92** [comment]
I found it strange that it was intended behavior because all other windows which let you input amounts or weights don't do this, only on this specific editing window. To me not changing it makes the most sense but it's not a big deal really!

**Comment by paulzakin** [comment]
I’ll chat with my partner and see what she thinks

**Comment by paulzakin** [comment]
Deployed - let me know what you think!

**Comment by sgomez92** [comment]
I'ts perfect! Adding to total count was the best choice, as subtracting from current could lead to confusion.
Thanks a bunch!

**Comment by sgomez92** [comment]
It's good, thanks!
